### ISSUE TITLE
Syntax error when trying to load BIOS.js

### ISSUE THREAD

**Issue by noahm888** [mrmakeit/OCJS#14]
When attempting to boot with the EEPROM (JS BIOS) I get this message:

error: failed loading bios: bios:1: syntax error near 'dec2string'

Seems like the computer is having trouble parsing the javascript

Details:
Minecraft 1.10.2
Added your mod and the latest OC to Project Ozone Lite

**Comment by mrmakeit** [comment]
It looks like you may somehow have ended up with a different version of Rhino.  I'm reuploading with rhino embeded.  Could you download the 0.5.1 release from the releases tab here on Github?

**Comment by noahm888** [comment]
Yes I will try that. Thank you

**Comment by noahm888** [comment]
Ok, downloaded the new 0.5.1 release, but the issue persists

**Comment by mrmakeit** [comment]
Just pulled up a new instance, and it looks like you may have left the CPU in the `Lua` architecture.  You'll need to pull out the CPU and sneak-use it till it says `Architecture: JavaScript`.

**Comment by mrmakeit** [comment]
I'm going to mark this invalid for now.  If you still have an issue, feel free to leave another comment.

**Comment by noahm888** [comment]
ah, did not realized I needed to do that. Thanks!
