### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#15]
using NodeJS?*
wich JavaScript Version is it?*

how to install? (Curse/Twitch Version? if it is a mod?), found it on patreon (should stand here or at oc.cli too ^^)

*sorry, didnt found it where it stands, if it stands somewhere ^^"

**Comment by mrmakeit** [comment]
It uses Rhino from mozilla, which has a list of supported features [here](http://mozilla.github.io/rhino/compat/engines.html).

It's on curseforge as an alpha, so it wont show up on the curse/twitch client (see #16), but it is available [here](http://minecraft.curseforge.com/projects/ocjs/) and in the releases tab here on github.
