### ISSUE TITLE
Console Spamming

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#18]
is there a way to deactivate the Console Spamming (Server Console + log)?

**Comment by mrmakeit** [comment]
Not at the moment.  I'll look into adding that, but while in alpha/beta, there will likely be quite a bit of spam.  The extra info helps while debugging logs.
I'll leave this open till that option is added.

**Comment by mrmakeit** [comment]
Also, most of that comes from computer.print statements inside the bios.  Feel free to remove those lines in the mean time.

**Comment by mrmakeit** [comment]
3baad6a fixes this.
