### ISSUE TITLE
Question about JS

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#21]
(Could be a dump question ^^")
Why not using the Chrome JS? 
so far i have seen it there, it brings more info in an error when in eval() "mode"

**Comment by mrmakeit** [comment]
V8 ("chrome js") is a C++ execution environment, which requires building cross-platform native libraries.  I've been looking at doing this for efficiency, but it requires a much broader build environment, and I still need a Java version for compatibility.  OpenComputers does this with Lua for much the same reason.

References: https://github.com/v8/v8

**Comment by hasezoey** [comment]
(too much at this? https://github.com/eclipsesource/J2V8 )
i understand what you mean .... 
(i dont know much about Java / dont understand much ^^")

**Comment by mrmakeit** [comment]
I hadn't seen that project yet, so I'll keep it in mind while working on the native library.  Thanks.

**Comment by hasezoey** [comment]
Ok, thanks for answering this Question ^^
(because i thought V8 would be better for this project)

**Comment by mrmakeit** [comment]
My main issue is that most of these are compilers not interpreters, so pausing execution when invoke runs out of requests for a particular tick doesn't work.  I'm looking at js-interpreter to cover this, so it may not matter in the end.

**Comment by hasezoey** [comment]
Found this https://stackoverflow.com/questions/6369919/how-to-embed-v8-in-a-java-application

**Comment by hasezoey** [comment]
I would be good, for an OS to have an Event Loop, like in Nodejs, would it possible to make such one, or include Nodejs?
It would be good, because of like settings global values, that are still there, not like yet where it executes the script and then re-executes the script.

what it would give:
- one time executeing the script, not always re-executeing
- so far i have seen no `eval` is required, because settings nodejs process directly
- you could controll the NodeJS process better (so far i have seen it)
- good use of Timeouts / loops / waiting things - what would not crash / timeout the Server
- it would be possible to create events, where the script that is executet could hook into it (like the user script can do something like `event.on('key_down', () => {}) //callback`) (i mean it that the OS could create these Events and the user script (executet over the os) could hook into it)

( https://eclipsesource.com/blogs/2016/07/20/running-node-js-on-the-jvm/ )

( hope its understandable what i wrote >w< )

**Comment by mrmakeit** [comment]
While this would make since in most cases, Unfortunately, the engine has to only execute when OC gives it permission to.  Since the engine has to be stalled every tick, and invoke requests are limited per tick, I currently chose to execute a function provided by the BIOS (or anywhere, really), so that invoke callbacks can be processed, and so the script quits to allow the engine to be stalled.  Unfortunately, I don't see a way to pause V8 execution mid-script to allow for invoke calls to be delayed to the next tick.  As for an event loop, with the computer.next function, it should be possible to implement an event look using that.  That was my plan originally, at least.

**Comment by mrmakeit** [comment]
Also, it appears that j2v8 has to be bundled for a particular machine version.  Since the distributed jar needs to be cross-platform, I can't use j2v8 directly.  I'm still looking to see if there is a way to build and distribute a multi platform version (including windows, mac, and linux,) but C++ isn't my forte, so that may depend on having someone with experience help out.

**Comment by hasezoey** [comment]
>  so that invoke callbacks can be processed, and so the script quits to allow the engine to be stalled. Unfortunately, I don't see a way to pause V8 execution mid-script to allow for invoke calls to be delayed to the next tick.

is it not enought to have a callback, what will be called when the invoke has finished? / or a promise?

**Comment by hasezoey** [comment]
> Also, it appears that j2v8 has to be bundled for a particular machine version. Since the distributed jar needs to be cross-platform, I can't use j2v8 directly. I'm still looking to see if there is a way to build and distribute a multi platform version (including windows, mac, and linux,) but C++ isn't my forte, so that may depend on having someone with experience help out.

readed https://github.com/eclipsesource/J2V8#building-j2v8 and there i only see "J2V8 uses a cross-platform, cross-compiling build-system written in Python."

**Comment by hasezoey** [comment]
+ JS is a bad option, when it needs to be limited x3 - but still it is a good option to program on, but bad to be limited

**Comment by mrmakeit** [comment]
The lua interpreter handles this by doing actual interpretation, not compiling to JVM bytecode, so it's significantly slower, but handles interruptions far better.  My hope is that one of the other projects I've been looking into can provide the same features to OCJS.
As for building j2v8, the cross-compiler requires significant resources and time to run, so if I were to use it, I'd prefer to make a separate project to allow building one time, vs building for every OCJS release.

**Comment by hasezoey** [comment]
i think i know what you mean

**Comment by hasezoey** [comment]
https://github.com/hasezoey/OCJS/tree/master-1.10.2/src/main/resources/OS/init.js
my current OS
so how im thinking, i would need an event loop - like for the `global.pos` - to save the last wrote line - to get it in the next "tick" and add it to there ^^ - any other thing how to make it? (except filesystem)

**Comment by mrmakeit** [comment]
Looking good, but be aware that while invoke calls to the same address may execute in the order called, it's not guaranteed, and certainly wont work across multiple components/addresses, as different components have different invoke limits.

**Comment by hasezoey** [comment]
I'm aware

im currently not invoke-ing much at the time, only defined function that do it, when needed
I try to descripe much as possible in the OS

**Comment by mrmakeit** [comment]
For the event loop, you could create an event function that parses an event list.  Global objects are retained between calls to the function passed in computer.next so maintaining a list should be simple enough.

**Comment by hasezoey** [comment]
Oh thanks for `computer.next()` ... didnt thought on that x3

**Comment by hasezoey** [comment]
why was this still open?
