### ISSUE TITLE
Return of computer.invokeSync() 

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#22]
What happens:
The Return of `computer.invoke()` is always something like `[Ljava.lang.Object;@15ca1b9e` (after the @ is always something other) 

What i expect:
That it returns a bool of is maked or not (or a translateable variable)

What i used: 
```js
var t = computer.invokeSync(gpu, 'set', [1, 1, "Hello"])
computer.print(t) //still the same when "t.toString()"
```

**Comment by mrmakeit** [comment]
invokeSync will return a list object that contains all the response values that the method returns.  gpu.set returns a single boolean value.

Unfortunately, the current handling of invokeSync doesn't use javascript native objects, so .toString doesn't do it's job very well.  I'm adding some code that will make invokeSync more robust, but for the time being, you'll need to handle the response appropriately(fetching the index of the response you need)

Suggested code:
```js
var t = computer.invokeSync(gpu,'set', [1,1,"Hello"])
if(t){ //check if invoke ran out of time
  computer.print(t[0])
}
```

**Comment by hasezoey** [comment]
because the invokeSync return an array, should forEach work,
Testet:
```js
var gpu = getComponentList('gpu')[0];
var gpu_res = computer.invokeSync(gpu, 'maxResolution', []);
var y = 2;
gpu_res.foreach((item) => {
    term.write(1, y, item);
    y+1
});
```
result in only printing oneline with `500`

**Comment by mrmakeit** [comment]
cb will receive the response from the method as parameters
eg: 
```js
cb = function(marked){
  computer.print("gpu marked successfuly")
}
computer.invoke(gpu,'set', [1,1,"Hello"],cb);
```
error will get a list with one object, the error message returned by the method.

As for the 500, invokeSync doesn't return an actual array, but an object that is array-like, so it doesn't work with foreach.

Also, invokeSync only works a handful of times per loop before returning false, due to the invoke count limits created by opencomputers.  You'll need to watch for that.

Take a look at the methods [here](https://github.com/mrmakeit/OCJS/blob/f11cd24a052350fea82170250ce95a65d405b7e3/src/main/java/me/mrmakeit/ocjs/ComputerAPI.java#L43)

**Comment by hasezoey** [comment]
`org.mozilla.javascript.EvaluatorException: Can't find method me.mrmakeit.ocjs.ComputerAPI.invoke(string,string,object,function). (<bios>#42(eval)#42)`
 the line `#42` is
```js
computer.invoke(gpu, 'set', [x, y, text.toString()], (obj) => { // this
            computer.invokeSync(gpu, 'set', [1, 1, obj.toString()]);
            cb();
        })
```

**Comment by hasezoey** [comment]
`org.mozilla.javascript.EvaluatorException: Can't find method me.mrmakeit.ocjs.ComputerAPI.invoke(string,string,object,function). (<bios>#42(eval)#42)`

```js
computer.invoke(gpu, 'set', [x, y, text.toString()], (obj) => { //this is line 42
            computer.invokeSync(gpu, 'set', [1, 1, obj.toString()]);
            cb();
        })
```

**Comment by mrmakeit** [comment]
there should be a second function on invoke for the error callback

**Comment by mrmakeit** [comment]
```js
computer.invoke(address, method, params, successCallback, errorCallback)
```

**Comment by hasezoey** [comment]
`if (typeof cb !== 'function') cb = () => { };`? (replace `cb` with the callback you want)
to not must have the error callback ^^

im trying to make a simple OS ^^

**Comment by mrmakeit** [comment]
computer.invoke is a java method that is lifted to javascript, so there isn't a way to remove the errorCallback requirement at this time.  I'll keep it in mind while i work on the synchronous arch.

**Comment by mrmakeit** [comment]
Actually, might I recommend using [ocjs-emulator](https://mrmakeit.github.io/OCJS-Emulator/master/)? that emulator more closely represents what the synchronous arch will support.

**Comment by hasezoey** [comment]
Sorry, i dont really understand the ocjs emulator, i test it directly ingame, on a server, with external edit of Visual Studio 17, and directly execute it in the pc (because try to make OS)

**Comment by hasezoey** [comment]
- should be referenced

- Closing because of #26
