### ISSUE TITLE
Keyboard Input

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#23]
How to get Keyboard input?

already looked in https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/openos/lib/keyboard.lua
but didnt found anything how to get, only definitions...

**Comment by mrmakeit** [comment]
Keyboard input puts events on the signal stack. you can pull them with computer.pullSignal()

**Comment by hasezoey** [comment]
has the `computer.pullSignal()` a callback?, or is it sync?
because i never got any signal when i pushed something

**Comment by mrmakeit** [comment]
the object should have multiple values.

**Comment by hasezoey** [comment]
also it could be that it is an java array, but at me come only `{"name":"key_down"}` and `key_up`

**Comment by mrmakeit** [comment]
Your right.  The response is an object with keys `name` and `args`.  the key code should be in args

**Comment by hasezoey** [comment]
at me it gives only what stands in the previous, also only "name"

**Comment by mrmakeit** [comment]
Move to nashorn aleviated the need to use NativeObjects over an Object array, so now pullSignal should return an array of (name,arg1,arg2,...) as expected.  Check the change_to_nashorn branch and see if that solves the problem.

**Comment by hasezoey** [comment]
does function now with `onSignal`
