### ISSUE TITLE
PC makes Timeout

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#24]
Idk why it comes sometimes and the other time not.

`Dec 21, 2017 11:10:23 PM io.netty.util.ResourceLeakDetector reportUntracedLeak
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.`

when i start the ingame PC...

- before i added this, it was not happened
```js
if (typeof text !== 'string') {
    cb(false);
    return;
}
if (text.length == 0) {
    cb(false);
    return;
}
```

It Makes the server waiting or so that the Clients get Timeoutet and cant re-join
and after some time ~20sec the server goes out (closes "normaly")

**Comment by hasezoey** [comment]
- found a reason, added to Wiki home 
it was an infinte while loop, to detect a Signal - still trying to get it to work

**Comment by mrmakeit** [comment]
Ya, part of the missing cpu and ram management.  I'll have a fix for it soon.
