### ISSUE TITLE
filesystem

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#25]
`computer.invokeSync(filesys, 'list', ['/'])[0]` returns `[Ljava.lang.String;@23bc8748`
+ when it is only a string, it would be good here when the invokeSync returns a real (JS) Array for `forEach`

**Comment by mrmakeit** [comment]
I'm working on a wrapper to handle invokeSync returns better, but I couldn't find a way to make an acutal JS array from inside the Java function.

**Comment by mrmakeit** [comment]
I've opened #26 to cover all the issues with invokeSync returns.
