### ISSUE TITLE
Wrap invoke calls to handle wierd outputs.

### ISSUE THREAD

**Issue by mrmakeit** [mrmakeit/OCJS#26]
This issue should cover unexpected returns from the callback passed to invoke, as well as the direct return from invokeSync.  
Unfortunently, the Java Object[] isn't translated to a real JS Array, and there doesn't appear to be a simple way to create a JS array from inside Java land.

**Comment by hasezoey** [comment]
found this: http://www.rgagnon.com/javadetails/java-0183.html

**Comment by mrmakeit** [comment]
Closing as nashorn correctly converts Object[] to a JS Array.
