### ISSUE TITLE
[Question] Rhino Version

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#27]
Wich Version of Rhino is currently implementet (/ is it higher than ES2015?)
because things like
```js
function test(param = 'default param') {
}
```
does here not function
( gives `Syntax Error: missing formal parameter` back)
readed https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Functions/Default_parameters
means it should function in Rhino too, so i would ask:
1. wich Version is currently used?
2. if not newest, could you update?

**Comment by mrmakeit** [comment]
The current version of Rhino is 1.7.7.2, which is (unfortunately) the latest version.  The feature list is (here)[http://mozilla.github.io/rhino/compat/engines.html].  It supports all of ES2015, and some new ES6 features.  Remember that ES6 has now been broken down by feature sets, so supported features may vary from engine to engine.

**Comment by hasezoey** [comment]
i ask because this code hwat you see above, should work with ES2015, and should be default to work in js ...
