### ISSUE TITLE
Support ES6+

### ISSUE THREAD

**Issue by pfgithub** [mrmakeit/OCJS#28]
I was working on making an OS for this, but without supporting ES6 it makes it much harder.

**Comment by mrmakeit** [comment]
Sadly, Rhino doesn't appear to be receiving any new updates, so until I can find a more stable embedded JS Interpreter, there isn't much I can do.  I am looking to add a [JS-Interpreter](https://github.com/NeilFraser/JS-Interpreter) version to handle memory/cpu/syncronous invoke, but still only supports a small subset of ES6.  If you have any suggestions for a fully interpreted library that supports ES6, I'm all ears.

**Comment by hasezoey** [comment]
(JS Interpreter for Java)

**Comment by pfgithub** [comment]
The java v8 bindings seem like they would work but it might have cross platform problems

**Comment by mrmakeit** [comment]
Probably, but I haven't found a way to manage execution time and memory on V8, which limits it's public use.  I'll end up adding it as an alternative to nashorn, once I've got those pieces figured out.

**Comment by mrmakeit** [comment]
I can go ahead and add babel as a pre-compute step when running nashorn scripts.  Would that work for you @pfgithub?

**Comment by mrmakeit** [comment]
3baad6a fixes this.
