### ISSUE TITLE
Crashed when intializing game

### ISSUE THREAD

**Issue by FuYang001** [mrmakeit/OCJS#30]
Crash report:https://pastebin.com/9qcc1Ku7
OCJS 0.6.0 for 1.7.10

**Comment by mrmakeit** [comment]
Try the 0.6.1 release.

**Comment by mrmakeit** [comment]
https://github.com/mrmakeit/OCJS/releases/download/0.6.1/ocjs-0.6.1-1.7.10.jar

**Comment by FuYang001** [comment]
Thanks! Game runs fine!
