### ISSUE TITLE
Shortening / better Errors

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#36]
when executing ES6 Code (or in mode) it gets shortend ... could it be to not make it shortend?
For Better Error output
/
or in the whole, could there be a better Error method?

**Comment by hasezoey** [comment]
how to configure babel: https://babeljs.io/docs/usage/babelrc/
all options: https://babeljs.io/docs/usage/api/

**Comment by mrmakeit** [comment]
`computer.error` just passes the error up to the OC error handler, which is the same handler that is invoked if an unhandled error is thrown, so the code on #37 will have the same result with the try..catch as without.

Babel config is handled by `LoaderAPI.java`'s eval function, doesn't quite work like the CLI babel.

As for shortening, it appears that the minification occurs when passing the babel results back to Java, and is not babels fault.  At this point, I'm not 100% sure how to fix the issue, and with the babel arch giving more and more issues, while remaining as slow as it is, I may just scrap it in exchange for working on J2V8 support, as Nashorn is just a stopgap when native support is unavailable.

**Comment by hasezoey** [comment]
could you give me the line where it is passing back / the whole babel section? (blob link?)

**Comment by mrmakeit** [comment]
https://github.com/mrmakeit/OCJS/blob/61d01bd640438edaa35f188738c1b2dbb7918684/src/main/java/me/mrmakeit/ocjs/LoaderAPI.java#L47

**Comment by mrmakeit** [comment]
It's getting late here, so I'm going to head off for the night.  I'll see where this is at in the morning.

**Comment by hasezoey** [comment]
see you tomorrow ^^

**Comment by mrmakeit** [comment]
Moving discussion to #58.
