### ISSUE TITLE
Initial EEPROM

### ISSUE THREAD

**Issue by mrmakeit** [mrmakeit/OCJS#4]
OC includes an eeprom that can be crafted to get the computers going.  Should do the same here.

**Comment by mrmakeit** [comment]
It really has be quite some time since I've touched this repository.  Seems I already have one of these.  Leaving open to verify it's set up correctly, then I'll close.

**Comment by hasezoey** [comment]
The EEPROM should be craftable

**Comment by mrmakeit** [comment]
Since the mod is still Alpha, and the eeprom can be copied from a running LUA computer, I haven't added any crafting recipes yet.  If you have an idea for the recipe, feel free to leave it here, but no promises on adding it just yet.
