### ISSUE TITLE
something is brocken when cloning

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#47]
When i clone and run `./gradlew setupDevWorkspace` and the `./gradlew build` and `./gradlew runClient` it all works, but when i try to import (/open) it in Eclipse it gives much errors, like that all is wrong (because forge is not referenced and open computers) but then it still gives me errors in NashornAPI that it dont know what "net.minecraft.*" is

~3days ago i already cloned it and all worked, but now it dosnt anymore

what am i doing wrong?

**Comment by mrmakeit** [comment]
you also need to run `./gradlew eclipse` to setup the eclipse environment.

**Comment by mrmakeit** [comment]
also, make sure you have the latest open computers jar file inside `run/mods` for `runClient` as I don't think the default api lib includes the binaries.

**Comment by hasezoey** [comment]
~~what do you use? (eclipse is the "only" thing i know that supports java in a useful way)~~

**Comment by mrmakeit** [comment]
I use several plugins with either vim or emacs, depending on which computer I'm using.
