### ISSUE TITLE
[Question] about computer.sleep

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#50]
the time that must be defined, what type is it? (not specified in the wiki)
milliseconds?
seconds?

**Comment by mrmakeit** [comment]
I think it's minecraft ticks? But I'm not sure.  It's the same unit as the lua sleep function

**Comment by hasezoey** [comment]
its seconds: https://ocdoc.cil.li/api:non-standard-lua-libs#operating_system_facilities
