### ISSUE TITLE
[Question] Upgrading to JDK 9?

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#55]
as i read, in JDK 9 Nashorn (JS Engine) gets some ECMA 6 featuers,
so i would ask is it possible (from minecraft & forge) to use *(/ upgrade)* to JDK 9? ~~Java 9?~~

**Comment by mrmakeit** [comment]
I think the nashorn.jar included is from JDK 9.  Unfortunently, upgrading to JDK 9 itself isn't an option due to OC requirements.
