### ISSUE TITLE
[Paused][Critical Issue] Crash when adding / settings a number in onSignal

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#56]
Minecraft ~~the JVM~~ crashes after a while (and takes 100% of CPU and more and more RAM) when doing in the onSignal loop things like 
```js
var num = 0;
onSignal = function() {
    computer.sleep(0);
    num++;
}
```
(PS: idk if this is all the code needed for the crash, when not, i could supply more)

**Comment by mrmakeit** [comment]
I've marked this as High Priority, but I'll need the full log and code being executed.

**Comment by hasezoey** [comment]
sorry there is no log to be provided, because the last things that stands there is from the last loop, because there is nothing being executet what would write to the log
(and sorry for saying crash, i meant heavy freezing (forever))

**Comment by mrmakeit** [comment]
The code above doen't seem to replicate the issue.  I'll need the minimum code to reproduce before I can continue.

**Comment by hasezoey** [comment]
here: https://github.com/hasezoey/OCJS_OS/blob/crit_crash/OS when using the `devinit_ES6` (and compiling with babel) it should be the freeze

**Comment by hasezoey** [comment]
i tested it again, it dosnt come anymore (i dont get the freeze to come anymore)
so, i will Close / Pause this Issue
